package server

import (
	"encoding/hex"
	"testing"
)

// Frames generated by the real y-protocols/awareness encoder (see W99):
// clientID 0xDEADBEEF (multi-byte varint), a user state and its removal.
const (
	realAnnounceHex = "01effdb6f50d01347b2275736572223a7b226e616d65223a224ac3a972c3a96d696120f09f9a80222c22636f6c6f72223a2223666632643630227d7d"
	realRemovalHex  = "01effdb6f50d02046e756c6c"
)

func TestParseAwarenessRealFrames(t *testing.T) {
	announce, _ := hex.DecodeString(realAnnounceHex)
	entries, ok := parseAwareness(announce)
	if !ok || len(entries) != 1 {
		t.Fatalf("announce: ok=%v entries=%d", ok, len(entries))
	}
	e := entries[0]
	if e.clientID != 0xDEADBEEF || e.clock != 1 || e.removed {
		t.Fatalf("announce entry = %+v", e)
	}

	removal, _ := hex.DecodeString(realRemovalHex)
	entries, ok = parseAwareness(removal)
	if !ok || len(entries) != 1 {
		t.Fatalf("removal: ok=%v entries=%d", ok, len(entries))
	}
	e = entries[0]
	if e.clientID != 0xDEADBEEF || e.clock != 2 || !e.removed {
		t.Fatalf("removal entry = %+v", e)
	}
}

func TestEncodeAwarenessRemovalRoundTrip(t *testing.T) {
	src := map[uint64]uint64{0xDEADBEEF: 7, 3: 1}
	entries, ok := parseAwareness(encodeAwarenessRemoval(src))
	if !ok || len(entries) != 2 {
		t.Fatalf("ok=%v entries=%d", ok, len(entries))
	}
	seen := map[uint64]uint64{}
	for _, e := range entries {
		if !e.removed {
			t.Fatalf("entry not marked removed: %+v", e)
		}
		seen[e.clientID] = e.clock
	}
	// Clocks must be bumped past the last announced value, or clients ignore
	// the removal as stale.
	if seen[0xDEADBEEF] != 8 || seen[3] != 2 {
		t.Fatalf("clocks = %v", seen)
	}
}

func TestParseAwarenessMalformed(t *testing.T) {
	for _, bad := range [][]byte{
		{},                       // empty
		{0x05},                   // promises 5 entries, delivers none
		{0x01, 0xff},             // clientID varint truncated
		{0x01, 0x01, 0x01, 0x30}, // string length runs past the buffer
		{0xff, 0xff, 0xff, 0x7f}, // absurd entry count (>1024)
	} {
		if _, ok := parseAwareness(bad); ok {
			t.Fatalf("accepted malformed frame % x", bad)
		}
	}
}

func TestVarUintRoundTrip(t *testing.T) {
	for _, v := range []uint64{0, 1, 127, 128, 300, 0xDEADBEEF, 1<<63 - 1} {
		buf := appendVarUint(nil, v)
		got, n := readVarUint(buf)
		if got != v || n != len(buf) {
			t.Fatalf("v=%d got=%d n=%d len=%d", v, got, n, len(buf))
		}
	}
}
