package server

import (
	"archive/zip"
	"fmt"
	"net/http"
	"sort"
	"strings"
)

// The downloadable agent skill.
//
// The complaint this answers, in his words: agents forget the rules the moment
// the context is gone, and he has to point at them again every time. That is
// not an agent being careless — it is where the instructions were kept. A rule
// that lives in a chat message lives exactly as long as that chat.
//
// So the skill has TWO parts, and the second is the point:
//
//  1. SKILL.md — the playbook. Loaded when the skill is invoked.
//  2. The FIRST INSTRUCTION IN IT is to write a short block into the repo's own
//     agent file (CLAUDE.md, AGENTS.md). That file is read at the start of every
//     session, by every agent, forever. The skill's job is to make itself
//     unnecessary.
//
// A generic skill could be a static file in the repo. This one is generated by
// the instance, because the useful parts are things only the instance knows:
// its own address, which workspaces exist and their ids, and the workspace
// rules somebody actually wrote. A playbook that says "connect to your Salt
// instance" is the kind of documentation that gets skimmed and forgotten; one
// that says "the Entwicklung workspace is 70bbc4e3… and here are its rules" is
// followed, because there is nothing left to look up.
//
// Everything here is generated from what the CALLER may see: the workspace list
// is the caller's, and the rules come with it. No permission decision is made
// in this file — it renders what workspacesFor already returned.

// skillDoc is one file in the bundle.
type skillDoc struct{ name, body string }

// skillWorkspace is the little of a workspace the bundle needs. Its own type
// rather than the JSON one: everything else on that struct (roles, proposals,
// logos) would be noise here, and half of it must never be written into a file
// somebody commits to a repository.
type skillWorkspace struct{ ID, Name, Rules string }

// skillWorkspaces lists what this person is a member of. Rows are drained
// before anything else touches the database — one connection.
func (s *Server) skillWorkspaces(userID string) []skillWorkspace {
	rows, err := s.db.Query(`
		SELECT w.id, w.name, COALESCE(w.rules, '')
		FROM workspace_members m JOIN workspaces w ON w.id = m.workspace_id
		WHERE m.user_id = ? ORDER BY w.is_personal DESC, w.created_at`, userID)
	if err != nil {
		return nil
	}
	defer rows.Close()
	var out []skillWorkspace
	for rows.Next() {
		var x skillWorkspace
		if rows.Scan(&x.ID, &x.Name, &x.Rules) == nil {
			out = append(out, x)
		}
	}
	return out
}

// buildSkill renders the whole bundle for one caller and one chosen workspace.
func (s *Server) buildSkill(u *user, base string, chosen string) []skillDoc {
	all := s.skillWorkspaces(u.ID)
	// The chosen workspace goes first and carries the rules; the rest are listed
	// so an agent knows what else it may be pointed at.
	sort.SliceStable(all, func(i, j int) bool { return all[i].ID == chosen && all[j].ID != chosen })
	var main *skillWorkspace
	for i := range all {
		if all[i].ID == chosen {
			main = &all[i]
			break
		}
	}
	if main == nil && len(all) > 0 {
		main = &all[0]
	}

	return []skillDoc{
		{"saltmd/SKILL.md", s.skillMain(base, main, all)},
		{"saltmd/reference/tools.md", skillTools()},
		{"saltmd/reference/block.md", skillBlock(base, main)},
		{"saltmd/README.md", skillReadme(base)},
	}
}

// skillMain is what the agent reads when the skill is invoked.
func (s *Server) skillMain(base string, main *skillWorkspace, all []skillWorkspace) string {
	name, id := "your workspace", ""
	if main != nil {
		name, id = main.Name, main.ID
	}
	var b strings.Builder
	fmt.Fprintf(&b, `---
name: saltmd
description: Work with this team's salt.md instance — the shared workspace where decisions, tasks and documentation live. Use at the START of any task that touches project knowledge, and whenever the user says to record, look up or file something. Also installs the standing rules into this repo so they survive a lost context.
---

# Working with salt.md

salt.md at %s is where this team keeps what it knows: decisions and why they
were made, what is being worked on, and the documentation that outlives the
conversation. It is reachable over MCP, so you can read and write it directly.

Main workspace: **%s** (`+"`%s`"+`)

## If the tools are not there yet

The endpoint is `+"`%s/mcp`"+`. Most clients sign in from that address alone —
they get a 401 that says where to authorize, a browser opens, a person approves
once, and nothing secret ever goes into a config file. A client that cannot do
that asks for a token instead; a person mints one in the workspace menu under
"Connect an agent", which also has the exact config line for your client.

**Ask for it rather than guessing.** No token is written into this bundle on
purpose — it gets unpacked into a repository, and repositories get pushed.

## Do this first, once per repository

Read the workspace rules and install the standing block, in that order:

1. `+"`get_workspace()`"+` — it returns this workspace's rules, written by the
   people who work here. **Follow them.** They beat anything in this file where
   the two disagree, because they were written for this workspace and this file
   was generated.
2. Append the block from `+"`reference/block.md`"+` to the repository's agent
   instructions — `+"`CLAUDE.md`"+` for Claude Code, `+"`AGENTS.md`"+` for most
   others. If both exist, both. If neither does, create the one that matches the
   agent you are.

Step 2 is the one that matters and it is easy to skip. A skill is loaded when it
is invoked; that file is read at the start of every session by every agent that
opens this repository. Without it, the next session starts from nothing and the
user has to explain all of this again — which is the exact problem this skill
exists to end.

## The standing rules

**Announce what you are working on, before you start.**

`+"```"+`
working_on(page_id: "<id>", agent: "claude", label: "<your name>",
           note: "what you are doing, in a few words")
`+"```"+`

Call it again with `+"`done: true`"+` when you finish. You stay listed until you
check out — nothing expires on you mid-task, and every other call you make on
that page counts as a sign of life. The note is the valuable half: "tidying the
file index" answers the question a person actually has, "working" does not.

**Set the status too.** Checking in says "I am on it"; the status says how far
it has got. Move it to in-progress BEFORE you start, not after.

**Leave notes as you go, not afterwards.**

`+"```"+`
note(page_id: "<id>", text: "approach A is out — cycles in the parent chain")
`+"```"+`

One line, no title, no place to choose. It joins that page's raw trail with the
time you wrote it. This is for what a write-up loses: the approach you tried and
dropped, the thing that surprised you, why you did NOT take the obvious road.

Write it AS it happens. That is the whole value — you are recording something
before you know how it ends, and a note can never be edited or removed
afterwards, by you or anyone. If one turns out wrong, add another saying so.

**Record the work where the work is.** A decision explained only in a chat
message is lost when that chat is. If it will matter next month, it belongs on a
page — with the reasoning, including the options you rejected. Nobody ever asks
why something was NOT built, which is precisely why it gets proposed a second
time.

**Read before you write.** `+"`search`"+` and `+"`get_page`"+` are cheap. A
second page about a thing that already has one is worse than no page.

`, base, name, id, strings.TrimRight(base, "/"))

	if main != nil && strings.TrimSpace(main.Rules) != "" {
		b.WriteString("## The rules of this workspace\n\n")
		b.WriteString("Written by the people who work here. They are the authority; re-read them\nwith `get_workspace()` when you return, because they change and this file does\nnot.\n\n")
		for _, line := range strings.Split(strings.TrimSpace(main.Rules), "\n") {
			b.WriteString("> " + line + "\n")
		}
		b.WriteString("\n")
	} else {
		b.WriteString("## The rules of this workspace\n\nNone are written yet. `get_workspace()` will say so too. If you notice conventions\nwhile working here, offer to draft some — `propose_workspace_rules` leaves a\nproposal for a person to approve, it never sets them itself.\n\n")
	}

	if len(all) > 1 {
		b.WriteString("## The other workspaces you can reach\n\n")
		for _, w := range all {
			if main != nil && w.ID == main.ID {
				continue
			}
			fmt.Fprintf(&b, "- **%s** — `%s`\n", w.Name, w.ID)
		}
		b.WriteString("\nEach has its own rules. Call `get_workspace(workspace_id)` before working in one\nyou have not seen.\n\n")
	}

	b.WriteString(`## What is in the box

` + "`get_page`, `search`, `list`, `create_page`, `write_content`, `update_page`" + `
for documents; ` + "`create_database`, `create_rows`, `query_rows`, `set_properties`," + `
` + "`update_schema`, `set_view`" + ` for collections. The full list with what each is
for is in ` + "`reference/tools.md`" + `, and ` + "`whoami`" + ` tells you at any moment what
this connection may actually do.

A note on vocabulary that will otherwise confuse you: what the interface calls a
**Collection** the tools call a **database**. Same thing. People see "Collection"
because it covers table, board, calendar and gallery and promises no SQL; the
tools keep ` + "`database`" + ` because renaming a tool breaks every agent config in
existence. Use the tool names in code and the word "collection" when writing to a
person.

## When something is refused

Call ` + "`whoami`" + `. It reports the token's scope, which workspaces it may reach,
and which actions are deliberately unavailable over MCP — which separates "I used
the wrong id" from "I am not allowed to do this", and those two need very
different next moves. Administrative things (users, tokens, instance settings)
are not missing by accident; they are closed to agents on purpose.
`)
	return b.String()
}

// skillBlock is the part that survives a lost context. Kept deliberately short:
// it is pasted into a file that every session reads, so every line costs
// attention on every future task, and a long block is one people delete.
func skillBlock(base string, main *skillWorkspace) string {
	name, id := "the workspace", ""
	if main != nil {
		name, id = main.Name, main.ID
	}
	return fmt.Sprintf(`# The block to install

Append this to `+"`CLAUDE.md`"+` / `+"`AGENTS.md`"+` at the top level of the
repository. Put it near the TOP — this is context for everything below it, not a
footnote.

Keep it short if you edit it. It is read at the start of every session, so every
line spends attention on every future task, and a long block is one somebody
deletes.

---

`+"```markdown"+`
## This project is documented in salt.md — use it at every step

Decisions, tasks and documentation live at %s,
workspace **%s** (`+"`%s`"+`), reachable over MCP. It is not a place to file
things at the end; it is where the work is recorded while it happens.

- **Before starting anything that takes more than a moment:** `+"`working_on(page_id, agent, label, note)`"+`,
  and `+"`done: true`"+` when finished. Set the task's status to in-progress at the
  same time — before you start, not after.
- **While working:** `+"`note(page_id, text)`"+` for what a write-up loses — the
  approach you dropped, the surprise, why not the obvious road. One line, written
  as it happens. Notes can never be edited or deleted, which is what makes them
  worth reading later.
- **Decisions go on a page, with the reasoning, including the options rejected.**
  A decision explained only in chat is lost when the chat is.
- **Read first.** `+"`search`"+` and `+"`get_page`"+` are cheap; a second page about
  something that already has one is worse than none.
- **The workspace has its own rules** — `+"`get_workspace()`"+` returns them and they
  outrank this block. Read them at the start of a session in a workspace you have
  not worked in yet.

If it is not recorded in salt.md, it did not happen.
`+"```"+`

---

## Why a file and not just this skill

A skill is loaded when it is invoked. `+"`CLAUDE.md`"+` and `+"`AGENTS.md`"+` are
read at the start of every session, by every agent, without anybody remembering
to ask. The rules were being forgotten because of where they were kept, not
because agents are careless — so the fix is where they are kept.
`, base, name, id)
}

func skillTools() string {
	return `# The tool catalogue, by what you want to do

Names are what you call; the interface's own words differ in one place, noted
below. ` + "`whoami`" + ` always reports what this particular connection may do.

## Finding things

| Tool | For |
| --- | --- |
| ` + "`search`" + ` | Full text across everything you may read. Start here. |
| ` + "`list(kind:)`" + ` | Enumerate pages, databases, workspaces, templates, files, tokens, users. |
| ` + "`get_page`" + ` | One page with its content; ` + "`include_children`" + ` for the subtree. |
| ` + "`get_collection`" + ` | A database's schema and views — call before writing rows. |
| ` + "`query_rows`" + ` | Rows with filters and sorting. |
| ` + "`get_links`" + ` | Backlinks for one page, or the whole graph with edge kinds. |
| ` + "`get_workspace`" + ` | Members (and their ids, for person properties), counts, and the rules. |

## Writing

| Tool | For |
| --- | --- |
| ` + "`create_page`" + ` | A new document. ` + "`parent_id`" + ` files it; ` + "`template_id`" + ` starts from a template. |
| ` + "`write_content`" + ` | Markdown into a page — ` + "`mode`" + ` append / prepend / replace. |
| ` + "`update_page`" + ` | Title, icon, tags, parent, favourite. |
| ` + "`create_database`" + ` | A new collection with its schema. |
| ` + "`create_rows`" + ` | Rows. Cheaper and safer than one create_page each. |
| ` + "`set_properties`" + ` | Property values on a row. Relations are ALWAYS a list, even for one. |
| ` + "`update_schema`" + ` | Add or change columns, including rollups and backrelations. |
| ` + "`set_view`" + ` / ` + "`delete_view`" + ` | Table, board, calendar, gallery — filters, sorting, grouping. |
| ` + "`upload_file`" + ` | A file onto a page. Large ones go over HTTP instead; the error says so. |
| ` + "`set_trashed`" + ` | Trash and restore. Nothing is destroyed. |

## Saying what you are doing

| Tool | For |
| --- | --- |
| ` + "`working_on`" + ` | Check in before a long task, check out after. Shown live to people. |
| ` + "`note`" + ` | One line onto a page's raw trail. Append-only, dated, permanent. |
| ` + "`comments`" + ` | Add, resolve or read comments — a conversation, aimed at people. |

Those first two look alike and are opposites. Presence is about NOW and has a
lifetime; a note is a dated fact that never changes. Use both.

## Two things that are easy to get wrong

**A relation property is always a list.** ` + "`[\"<id>\"]`" + `, never ` + "`\"<id>\"`" + `,
even with one target. This is the single most common failed write.

**Property values are written by ID, not by label.** ` + "`get_collection`" + ` gives
you both; a select option called "In Arbeit" may well have the id ` + "`in-arbeit`" + `,
and writing the label silently produces a value nothing matches.
`
}

func skillReadme(base string) string {
	return fmt.Sprintf(`# salt.md agent skill

Generated by the instance at %s, so the addresses, workspace ids and rules in it
are that instance's own.

## Install

**Claude Code** — put the `+"`saltmd/`"+` folder in either place:

    ~/.claude/skills/saltmd/       (every project)
    .claude/skills/saltmd/         (this repository only)

Then invoke it with `+"`/saltmd`"+`, or just ask to work with Salt.

**Other agents** — `+"`SKILL.md`"+` is plain Markdown with a small YAML header.
Anything that reads instruction files can use it: paste it, put it wherever that
agent keeps standing instructions, or hand it over as a file.

## The important part

The skill's first instruction is to copy a short block into this repository's
`+"`CLAUDE.md`"+` or `+"`AGENTS.md`"+`. Do not skip it — that file is what every
future session reads without being asked, and it is the reason the rules stop
getting forgotten. `+"`reference/block.md`"+` holds the block on its own if you
would rather paste it by hand.

## Keeping it current

Workspace rules change and this bundle does not. `+"`get_workspace()`"+` always
returns the live ones and outranks anything written here; download the skill
again when the instance itself has changed.
`, base)
}

// handleSkill serves the bundle as a zip.
func (s *Server) handleSkill(w http.ResponseWriter, r *http.Request) {
	u := requestUser(r)
	ws := r.URL.Query().Get("workspace")
	if ws == "" {
		ws = s.defaultWorkspaceFor(u)
	}
	if ws != "" && !s.isMember(u.ID, ws) {
		httpError(w, 404, "workspace not found")
		return
	}
	// publicShareBase, not publicBase: this address is written into a repository
	// and an agent will dial it from somewhere else entirely. The weaker
	// resolver falls back to the Host header, so downloading the skill from
	// http://192.168.1.50 would put THAT into the file — correct for the person
	// standing on that network, useless for a cloud agent. This one knows the
	// configured domain and the tunnel, and it is the same resolver the
	// "Connect an agent" dialog shows, so the two can never disagree.
	docs := s.buildSkill(u, s.publicShareBase(r), ws)

	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", `attachment; filename="saltmd-skill.zip"`)
	zw := zip.NewWriter(w)
	defer zw.Close()
	for _, d := range docs {
		f, err := zw.Create(d.name)
		if err != nil {
			return
		}
		if _, err := f.Write([]byte(d.body)); err != nil {
			return
		}
	}
}
