// Builds THIRD-PARTY-NOTICES.md — the one obligation almost every licence we
// depend on actually imposes: the notice has to travel with what you ship.
//
// salt.md ships as ONE binary with the frontend embedded, so "what you ship"
// includes both sides. Both are read here: Go modules from `go list`, npm
// packages from node_modules.
//
// Generated, never hand-kept. A hand-written list is wrong the first time
// somebody adds a dependency, and nobody notices, because nothing fails.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const LICENCE_FILE = /^(LICEN[CS]E|COPYING)/i;

function licenceText(dir) {
  if (!dir || !existsSync(dir)) return '';
  const file = readdirSync(dir).find((f) => LICENCE_FILE.test(f));
  return file ? readFileSync(join(dir, file), 'utf8').trim() : '';
}

// ---- Go ----
// `go list -m -json all` reports every module in the build, with the directory
// in the module cache where its licence file sits.
const goMods = [];
const raw = execFileSync('go', ['list', '-m', '-json', 'all'], { cwd: repo, maxBuffer: 64 << 20 }).toString();
for (const chunk of raw.split(/^\}$/m)) {
  const text = chunk.trim();
  if (!text) continue;
  let m;
  try {
    m = JSON.parse(text.endsWith('}') ? text : text + '\n}');
  } catch {
    continue;
  }
  if (!m.Path || !m.Version) continue;
  goMods.push({ name: m.Path, version: m.Version, licence: licenceText(m.Dir) });
}

// ---- npm ----
// Only what is actually shipped: dependencies, not devDependencies. Vite,
// TypeScript and Playwright build the thing and are not part of it.
const pkg = JSON.parse(readFileSync(join(repo, 'web/package.json'), 'utf8'));
const npmPkgs = Object.keys(pkg.dependencies ?? {}).map((name) => {
  const dir = join(repo, 'web/node_modules', name);
  let version = '';
  let id = '';
  try {
    const p = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    version = p.version ?? '';
    id = typeof p.license === 'string' ? p.license : (p.license?.type ?? '');
  } catch {
    /* not installed — it shows up as a gap below rather than vanishing */
  }
  return { name, version, id, licence: licenceText(dir) };
});

const all = [...npmPkgs, ...goMods];
const missing = all.filter((d) => !d.licence);

const out = [
  '# Third-party notices',
  '',
  'salt.md ships as a single binary with its frontend embedded, so every',
  'component below travels inside it. Each is used under its own licence,',
  'reproduced here in full.',
  '',
  'salt.md itself is AGPL-3.0 — see [LICENSE](LICENSE).',
  '',
  'Generated by `node scripts/licenses.mjs`. Do not edit by hand.',
  '',
  '## Summary',
  '',
  '| Component | Version | Licence |',
  '| --- | --- | --- |',
  ...npmPkgs.map((d) => `| ${d.name} | ${d.version} | ${d.id || '—'} |`),
  ...goMods.map((d) => `| ${d.name} | ${d.version} | — |`),
  '',
];
for (const d of all) {
  out.push(`## ${d.name} ${d.version}`.trimEnd(), '');
  if (d.licence) {
    out.push('```\n' + d.licence + '\n```');
  } else if (d.id) {
    // Some packages declare a licence and ship no text — @excalidraw/excalidraw
    // is one. Naming it is worth more than a blank, and the reader can find the
    // text by its SPDX id.
    out.push(`Declared as **${d.id}**. The package ships no licence text of its own;`);
    out.push(`the terms are those of the ${d.id} licence.`);
  } else {
    out.push('_This package declares no licence and ships no licence text._');
  }
  out.push('');
}
writeFileSync(join(repo, 'THIRD-PARTY-NOTICES.md'), out.join('\n'));

console.log(`  notices: ${npmPkgs.length} npm + ${goMods.length} Go → THIRD-PARTY-NOTICES.md`);
if (missing.length) console.log(`  without a licence file: ${missing.map((d) => d.name).join(', ')}`);
